course_pending: "pending"
course_started: "started"
task_quanlity: 1
params_all: "all"
params_pending: "pending"
params_started: "started"
params_finished: "finished"
status_pending: "pending"
status_started: "started"
pagination:
  per_page: 15
message_notice: "notice"
message_alert: "alert"
message_danger: "danger"
  per_page_member: 5
